language: node_js
sudo: false
node_js: '8'
env:
  global:
  - secure: U4VN6zdl70AQWIZh4VuseQHSas+6PMlGz6V3jiEMem4NoYpwwUnFwUzZpGIF+RHITG4VMiQ+VtJaeRGwrpiWh53q4aTjN8xhIlTXS91EsxgZJEBeyQUMIpKmV4R6AwaV1bViubjvdrOfk1D0kWJ8A2stndY5ndVP1OF5+d7LDvZWK2eLEieTElhkpSOJ/Qfxrmc+AwQJEw42Lnmv4RTSl7vDRnv0ZmRCsKtRWcseZzP2h5SD/L1T3gSoxXXyoZP/OItvpOsViiYjJzBryOfoi3CQEqT2dEFikTtNr3UyNm3xb1YnGzPyreR2dVlJLxOyn6B3WuuMhx5mlUJhrUMd8aE6P1khWG/5SjAAfVWorfKAzEqAPtqyFC4LtPexwY9JRoPSw0NiD0Ac6r2vJEtAPF4GnjQYUwWg2KVTZOgfLt8YbKNhnnQLdVXZoP6+WhvwR0z4U1VGMdfir02pzWhiLjHPC27NMasLxDC1DJgCjhC91MJ7XptWA7KWrXOQvZZofIFstypEJI8YaelSVGnIoxYuNILcdM2foMBzoxZcR/bo9BNHbGa6+j4rdF2GfeBxAQMpl+7DR0SCzrejgoNHTFpJC+q5xUNUCzJYOQYMI2OFFxfyRjjJsHyZeI1HVWcLY6nW+V5JuFSA7GDFCGkO0uoZBVpw/iYvvHIkRcQHnhY=
  - secure: dHuzqnkk2GwsXIfik02d24OeEs7NPY6thfALvBCB1hGr0IpOYkzlZa1qp1YECGlL3xr9f2Rr77BCvBnmw2hPKzsbxS5AWlZfIipdh6SjaZMxGFLOlPqS/1biz27W0gOOBxEHShzoDALwQVRaAmQonexwT1pIWd1ENAtNFKgpywZKcYwZdqZ4opfObZfKPSKqNLS8oNPLkusO300eNHigXK5EWPxy9InUyrDA3i6/FtkW2yk2ZD4csE9YFRShpFBHEtYThE5S8lvytnxZ0ecfwQPSBjRDaHIMu4xX09QncKcllMiiQgMxvFfPPdbMKyMj2qutP9zC346Bg+L1BpsZR02MaNSP7efIluPbgN10znwUzKbaonFbX5TKKUara2BuoTn3Gl/fMTDReQvJfc5nir/Ov01UDXC20j8Dk3V54jGUzUXfFSy9vRSAxM2QPhVTe7IoL+rSCFwc1DGcgMT2iZvNCdfsVxgw52DLfpIzPaww9E8/zWNB1jVrNxlghPv8b/r/CbA6rpwSVMkhxZ4qfrAo5PYTSfPLKQWz4eBpIBQkcs8jCXAFDWL0e/vYb5J4Y7yr8wZ0J34J93IscGJ2YG4vV0nYqrsbVtMUJstPB9kteuZ7dlR2q1C+cxRmPETgF/neQMfbzfaA45GqWiXCA8PqQrY1olCZl6AWoxr0FWo=
  - secure: BZCpNa+kZ3IJLiXyVtubAiW+7GMXZXRLPIW+LXq9OmP3/t6HeE6b+ZOGQpkVhpgP6aNo/qxRb0UMMk19RlulkCeVc4+pPmp8Zkt4GlXatryxOm0z/xc+F/UjKdOVhXvWYO2QPmsRQ5WJGuCCKPpAgqWmAf/7YHJDU0Zk/ZTl5Pcybf6BPq8YvPRr6K+3UmgJF4pZsiH3Ru5GN3YTsTxtYJV/7RQj3Wtvq7LzIbMHz9dvPeCJtST4yRcnrtCVB4kk+mZ7MnuhDhwTHr1xXCoN2lsWF5uDZ+ZL6E4ugRIDO/E9zhXeKmpiqkZMP8X5RXNH6dc0gBoMg64686SnRfxJYKKVb83/iWRpxsRWxv4Oyxne9fKzntKXM2pIJYVTY5XyEAHNKXFVC/T6kh4K8zHievutaEXvxicKry88Unpn00jb5BEAjLVBCKE+dyx4oU91OnzRFLpMk5dPOmWM9+axL3rnMWjXu+rb29wZzlbESajhFOxsEz4kdYKPyY22TmNR0LiRV4FBX807x7tzVlXo8vZVAOqZX+6OM4nbOet5XbYStFxXzy64r0n6V7Iodcjr2t176H4S362pE90uf7lLWzIH6IChEDSXZfS6mwUIjSvex4Kf92zgABGrX4Sus/mX9aP7qZz+jHr4Ak45ztPzqurZg4e/WbFoPq8KG6YCybg=
cache:
  yarn: true
install:
- yarn install
script:
- yarn test
before_deploy:
- yarn build
- yarn package
- yarn sign:webextension --key $sign_key --secret $sign_secret --id $sign_id
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: wBgLoMicSz7wHLlloFJzmjfY3ght4Prx0X1hCmMPWhEMCgY9iTe87HAGGZ9UFbf9xln+49uOVfAsa1ErTBuOsLbgi38SYeSKL6ccdFeyBjR4+4N7T+BXkS+iEkPw4c1ZgjNfHrd9cBnuGIADegGtQeQglS9W5tnWWhlRf1NIGgDYv4gGZyBUBl7ORCfy6oeo36wffhQ1ObUTyZTTEfdm726cQ2cP1+OnIp9RjQS2u66Z/E2tjm9uhrkstz41+yyD0NZS9IU6CODNNriapc1O6B5xWB+rnEv1QRZ4pU7p3cjbfZmnRImUwqQbJUFey2kb9QEwd8bmvs7ATw6xiy7U8iYJ8mxvV0XGFtPlOtOn6a+MO1pJzmEGJ1/kZ9aM8yLJ8R7tUYG8HbwccnY7N/xFgwNZFJ2Edy7PAWam632ScLNHgLd38hHStceCPag8do+aFmA/eE5flOvO8Mevm6JUSOF6UHItus4fALmof2ztYnbYiV/DqmzkLihhwiOcrrm+6kokfOYYXaaCKh2h4JacRzbzR9zf1V0/TcIWdlfMklqxVpe9ireUK8+LLSvR7IsQgXn7J5pfg69Q7S9QfPovWP6XmQ67t0U/k+70/nVNVHVnIBh2NwfF2ieXJpKdUZ74XqEOq9N1M8VNLHm54WeiGT3uKbnAdRL2VAUZhvSB4XU=
  file_glob: true
  file:
  - "./dist/crunchyroll_html5-*.xpi"
  - "./dist/crunchyroll-html5.user.js"
  - "./dist/firefox.xpi"
  - "./dist/webextension.zip"
  on:
    tags: true
    all_branches: true
